### ISSUE TITLE
18.04 acer笔记本无法启动wifi

### ISSUE THREAD

**Issue by omaidb** [ghostplant/web-ubuntu-mate#14]
昨天晚上找解决办法，发现这类问题还蛮多的
得到的解决办法是
sudo nano /etc/modprobe.d/blacklist.conf
最后一行加入：
blacklist acer-wmi
不过我还没试呢，今晚下班试一下
大佬您要不要看看是什么原因，关键词blacklist acer-wmi

**Comment by omaidb** [comment]
还有，点睡眠系统直接关机了

**Comment by ghostplant** [comment]
所以说这个应该是官方的驱动库目前缺省这么设置的，也许缺省这么设置是因为其他一些firmware可能会跟这个driver有冲突，这个只能等等，或者有launchpad账号的可以apport-bug到linux-image-generic。

**Comment by omaidb** [comment]
没launchpad账号，您可以代为提交嘛
ghostplant <notifications@github.com>于2018年3月8日 周四15:13写道：

**Comment by ghostplant** [comment]
apport-bug是一个命令，按照提示会自动检查本地出现问题的wifi型号并将其添加到bug正文中，因为我这边wifi型号没有问题所以汇报时候说不清楚。。

apport-bug不麻烦，终端输入 `apport-bug linux-image-generic`，按照中文提示下一步就可以了

**Comment by omaidb** [comment]
好的
ghostplant <notifications@github.com>于2018年3月8日 周四17:12写道：

**Comment by ghostplant** [comment]
那你就`apport-bug linux-image-generic`说blacklist acer-wmi以后才能使用wifi~

**Comment by ghostplant** [comment]
定期 sudo apt update && sudo apt dist-upgrade 来度过测试阶段的更新补丁。

**Comment by omaidb** [comment]
怎么把 — 口 X 调到左边？在右边好不习惯啊。还有chrome浏览器上方那么黑一条看起来好丑，能不能标签栏置顶啊

**Comment by ghostplant** [comment]
我建议你在chrome设置里面开启“使用系统标题栏和边框”。

如果所有应用统一调左，执行：`gsettings set org.mate.Marco.general button-layout 'close,minimize,maximize:'`

**Comment by omaidb** [comment]
已搞定
