### ISSUE TITLE
使用Dockerfile构建汉化不全

### ISSUE THREAD

**Issue by flyqieqq** [ghostplant/web-ubuntu-mate#23]
使用Dockfile构建Docker镜像不知为何还会出现汉化不全的现象。。。
文本编辑器、监控器什么的都是英文的...
请问这是为啥

**Comment by ghostplant** [comment]
您好，谢谢您的问题汇报。
经测试，此问题的确存在，经分析发现这个问题来自latest ubuntu:18.04的镜像问题，官方目前最新的18.04镜像中 `/usr/share/locale/zh_CN/LC_MESSAGES/` 没有包含任何语言文件（然而ubuntu:16.04最新镜像以及早期的ubuntu:18.04镜像是正常的），因此这个需要等待ubuntu官方解决语言文件丢失问题。

**Comment by ghostplant** [comment]
如果您采用官方的镜像构建任何其他应用：
```sh
docker run -it --rm ubuntu:18.04 bash
```
里面`/usr/share/locale/zh_CN/LC_MESSAGES/`也是为空的。

**Comment by ghostplant** [comment]
@flyqieqq 请更新最新构建脚本，重新构建镜像即可解决语言文件丢失问题：
参考：https://github.com/ghostplant/web-ubuntu-mate/commit/32c199c0eb3cd89466b563e259e67e89a7bdcbb1
