### ISSUE TITLE
关于镜像制作问题

### ISSUE THREAD

**Issue by trialley** [ghostplant/web-ubuntu-mate#24]
您好，我使用您构建的ubuntu镜像很久了，您做的镜像非常棒、非常好用。一直好奇您是通过什么方法将镜像精简到300-500mb的，可以分享一下方法吗？感谢！

**Comment by ghostplant** [comment]
参考：
1）squashfs-tools 对ubuntu镜像文件解包、封包；
2）mkisofs 重新打包 iso文件。
